name: CI
on: [push,workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ["1.20"]
    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go_version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go get -v -t -d ./...

      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.3"

      - name: Test
        run: go test -v ./...

      - name: Build
        run: make build
